---
    - name: Disable SELinux
      selinux:
        policy: targeted
        state: permissive

    - name: PMM                        | Add firewalld rule
      firewalld: port={{ item }} permanent=true state=enabled immediate=yes
      with_items:
          - 80/tcp
          - 443/tcp

    - name: PMM                        | Add script which show PMM URL
      copy:
        src: show-pmm-url
        dest: /var/lib/cloud/scripts/per-boot/show-pmm-url
        mode: 0755

    - name: PMM                        | Delete centos
      shell: cd /tmp; nohup sh -c "trap 'userdel -r centos' EXIT; sleep 600" </dev/null >/dev/null 2>&1 &

    - name: PMM                        | Delete vagrant
      shell: cd /tmp; nohup sh -c "trap 'userdel -r vagrant' EXIT; sleep 600" </dev/null >/dev/null 2>&1 &

    - name: PMM                        | Delete Azure user
      shell: cd /tmp; nohup sh -c "trap '/usr/sbin/waagent -force -deprovision+user && sync' EXIT; sleep 600" </dev/null >/dev/null 2>&1 &

